.PHONY: clean All

All:
	@echo "----------Building project:[ AresGameInput - Debug ]----------"
	@cd "AresGameInput" && "$(MAKE)" -f  "AresGameInput.mk"
clean:
	@echo "----------Cleaning project:[ AresGameInput - Debug ]----------"
	@cd "AresGameInput" && "$(MAKE)" -f  "AresGameInput.mk" clean
